#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 diskOS contributors
"""Generate i18n_tables.c (ASCII source, octal-escaped UTF-8) from i18n/strings.tsv.
Usage: python3 tools/generate_i18n.py [OUT]   (run from anywhere; default OUT = i18n_tables.c next to the sources;
the file is only rewritten when its content changes, so an unchanged build stays up to date)
Columns: en zh tw ja ko es pt it de fr ru = the LANG_* order of i18n.h with English (LANG_EN, index 2) as the key."""
import sys
from pathlib import Path
app = Path(__file__).resolve().parents[1]
COLS = ['zh', 'tw', 'en', 'ja', 'ko', 'es', 'pt', 'it', 'de', 'fr', 'ru']   # i18n_lang_t order
IDS = ['LANG_ZH', 'LANG_TW', 'LANG_EN', 'LANG_JA', 'LANG_KO', 'LANG_ES', 'LANG_PT', 'LANG_IT', 'LANG_DE', 'LANG_FR', 'LANG_RU']
# each language's name in its own script; stock resource variants set the list
NAMES = ['\u7b80\u4f53\u4e2d\u6587', '\u7e41\u9ad4\u4e2d\u6587', 'English', '\u65e5\u672c\u8a9e', '\ud55c\uad6d\uc5b4', 'Espa\xf1ol', 'Portugu\xeas', 'Italiano', 'Deutsch', 'Fran\xe7ais', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439']


def c_str(s):
    return '"' + ''.join(chr(b) if 0x20 <= b < 0x7f and chr(b) not in '"\\' else '\\%03o' % b for b in s.encode('utf-8')) + '"'


rows = []
for line in (app / 'i18n/strings.tsv').read_text(encoding='utf-8').splitlines():
    if not line.strip() or line.startswith('#'):
        continue
    rows.append(line.split('\t'))
head, rows = rows[0], rows[1:]
assert head == ['en', 'zh', 'tw', 'ja', 'ko', 'es', 'pt', 'it', 'de', 'fr', 'ru'], head
o = ['/* SPDX-License-Identifier: GPL-3.0-or-later */', '/* Copyright (C) 2026 diskOS contributors */',
     '/* GENERATED by tools/generate_i18n.py from i18n/strings.tsv - do not edit. */',
     '#include "i18n.h"', '']
o.append('const char *const i18n_lang_names[LANG_COUNT] = {')
for n in NAMES:
    o.append('    %s,' % c_str(n))
o.append('};')
col = {'zh': 1, 'tw': 2, 'ja': 3, 'ko': 4, 'es': 5, 'pt': 6, 'it': 7, 'de': 8, 'fr': 9, 'ru': 10}
seen = set()
for r in rows:
    assert len(r) == 11 and r[0] not in seen, r
    seen.add(r[0])
for c in COLS:
    if c == 'en':
        continue
    ents = sorted(((r[0], r[col[c]]) for r in rows if r[col[c]]), key=lambda e: e[0].encode('utf-8'))
    o.append('static const i18n_entry_t T_%s[] = {' % c.upper())
    for en, t in ents:
        o.append('    { %s, %s },' % (c_str(en), c_str(t)))
    o.append('};')
o.append('const i18n_table_t i18n_tables[LANG_COUNT] = {')
for c, i in zip(COLS, IDS):
    o.append('    [%s] = { 0, 0 },' % i if c == 'en' else '    [%s] = { T_%s, (int)(sizeof T_%s / sizeof T_%s[0]) },' % (i, c.upper(), c.upper(), c.upper()))
o.append('};')
out = Path(sys.argv[1]) if len(sys.argv) > 1 else app / 'i18n_tables.c'
text = '\n'.join(o) + '\n'
if not out.exists() or out.read_text() != text:
    out.write_text(text)
print('i18n_tables.c: %d strings' % len(rows))
