#!/usr/bin/env python3
"""Generate the small Source Han supplement without modifying vendored LVGL.

Usage: python3 tools/generate_cjk_supplement.py /path/to/SourceHanSansSC.otf
Requires lv_font_conv 1.5.3 in ../node_modules (or pass --converter).
The input font must be the SIL OFL-licensed Source Han Sans SC Regular.
"""
import argparse
from pathlib import Path
import re
import subprocess

app = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser()
p.add_argument('font', type=Path)
p.add_argument('--converter', type=Path, default=app.parent/'node_modules/lv_font_conv/lv_font_conv.js')
a = p.parse_args()
chars = ''.join(line.strip() for line in (app/'fonts/cjk-supplement.txt').read_text().splitlines()
                if line.strip() and not line.lstrip().startswith('#'))
out = app/'font_cjk_extra_16.c'
subprocess.run(['node', str(a.converter), '--font', str(a.font), '--symbols', ''.join(sorted(set(chars))),
                '--size', '16', '--bpp', '4', '--no-compress', '--no-prefilter',
                '--format', 'lvgl', '--force-fast-kern-format', '-o', str(out)], check=True)
s = out.read_text()
s = re.sub(r' \* Opts:.*\n', ' * Generated by tools/generate_cjk_supplement.py from fonts/cjk-supplement.txt.\n', s)
s = '/* SPDX-License-Identifier: OFL-1.1 */\n/* Source Han Sans SC. Copyright 2014, 2015 Adobe Systems Incorporated, with Reserved Font Name Source. */\n' + s
out.write_text(s)
print(out)
